######################################################################
# Automatically generated by qmake (3.1) Fri Apr 18 15:17:20 2025
######################################################################

TEMPLATE = app
TARGET = Client
DESTDIR = .

CONFIG -= windows
CONFIG += console

INCLUDEPATH += .
LIBS += -lws2_32

QT += core gui widgets

QMAKE_CXX = C:/Qt/Tools/mingw1310_64/bin/g++.exe
QMAKE_CC  = C:/Qt/Tools/mingw1310_64/bin/gcc.exe

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_UP_TO=0x060000 # disables all APIs deprecated in Qt 6.0.0 and earlier

# Input
HEADERS += acertijo.h jugador.h personaje.h pueblo.h zona.h \
    ficheros.h\
    protocoloMensages.h\
    PantallaAnadir.h \
    PantallaAnadirPersonaje.h \
    PantallaMenuAdministrador.h \
    PantallaResolverMisterio.h \
    iniciarSesion.h \
    menuInicio.h \
    menuInteraccionPersonaje.h \
    menuPrincipal.h \
    pantallaAnadirPueblo.h \
    pantallaAnadirZona.h \
    pantallaEliminar.h \
    pantallaModificar.h \
    registrarse.h \
    seleccionPantalla.h
SOURCES += acertijo.cpp \
           ficheros.cpp\
           protocoloMensages.cpp\
           PantallaAnadir.cpp \
           PantallaAnadirPersonaje.cpp \
           PantallaMenuAdministrador.cpp \
           PantallaResolverMisterio.cpp \
           iniciarSesion.cpp \
           jugador.cpp \
           main.cpp \
           menuInicio.cpp \
           menuInteraccionPersonaje.cpp \
           menuPrincipal.cpp \
           pantallaAnadirPueblo.cpp \
           pantallaAnadirZona.cpp \
           pantallaEliminar.cpp \
           pantallaModificar.cpp \
           personaje.cpp \
           pueblo.cpp \
           registrarse.cpp \
           seleccionPantalla.cpp \
           zona.cpp
